# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2023.11.17
_src_path: gh:scientific-python/cookie
backend: hatch
email: nstarman@users.noreply.github.com
full_name: Nathaniel Starkman
license: BSD
org: nstarman
project_name: units
project_short_description: Units 2.0
url: https://github.com/nstarman/units
vcs: true
